export const headColumns = [
  { title: "First Name", value: "firstName" },
  { title: "Last Name", value: "lastName" },
  { title: "Start Date", value: "startDate" },
  { title: "Department", value: "department" },
  { title: "Date of Birth", value: "dateOfBirth" },
  { title: "Street", value: "street" },
  { title: "City", value: "city" },
  { title: "State", value: "state" },
  { title: "Zip Code", value: "zipCode" },
];

export const employeesList = [
  {
    firstName: "Vivie",
    lastName: "Keyzor",
    startDate: "11/1/2022",
    department: "Services",
    dateOFBirth: "7/21/1993",
    street: "64 Cardinal Street",
    city: "Lincoln",
    state: "NE",
    zipCode: "68505",
  },
  {
    firstName: "Iggy",
    lastName: "Kimmel",
    startDate: "9/10/2022",
    department: "Research and Development",
    dateOFBirth: "12/25/1984",
    street: "7 Golf Course Circle",
    city: "Honolulu",
    state: "HI",
    zipCode: "96825",
  },
  {
    firstName: "Glynnis",
    lastName: "Maria",
    startDate: "7/31/2022",
    department: "Engineering",
    dateOFBirth: "3/19/1993",
    street: "88725 Packers Parkway",
    city: "Jackson",
    state: "MS",
    zipCode: "39210",
  },
  {
    firstName: "Shellysheldon",
    lastName: "Mitro",
    startDate: "3/9/2022",
    department: "Accounting",
    dateOFBirth: "7/8/2000",
    street: "7 Lerdahl Drive",
    city: "Richmond",
    state: "VA",
    zipCode: "23228",
  },
  {
    firstName: "Eartha",
    lastName: "McClements",
    startDate: "7/26/2022",
    department: "Product Management",
    dateOFBirth: "8/23/2000",
    street: "453 Birchwood Junction",
    city: "Houston",
    state: "TX",
    zipCode: "77095",
  },
  {
    firstName: "Onofredo",
    lastName: "Josef",
    startDate: "9/28/2022",
    department: "Accounting",
    dateOFBirth: "10/20/1986",
    street: "6637 Cascade Hill",
    city: "Colorado Springs",
    state: "CO",
    zipCode: "80920",
  },
  {
    firstName: "Nichol",
    lastName: "McElhargy",
    startDate: "7/29/2022",
    department: "Marketing",
    dateOFBirth: "11/18/1989",
    street: "5 Forest Street",
    city: "San Antonio",
    state: "TX",
    zipCode: "78225",
  },
  {
    firstName: "Poul",
    lastName: "Gribbell",
    startDate: "2/13/2022",
    department: "Research and Development",
    dateOFBirth: "12/3/1984",
    street: "745 Hermina Junction",
    city: "Colorado Springs",
    state: "CO",
    zipCode: "80995",
  },
  {
    firstName: "Viviene",
    lastName: "Rabier",
    startDate: "3/1/2022",
    department: "Legal",
    dateOFBirth: "2/11/1995",
    street: "070 Tennessee Place",
    city: "Fresno",
    state: "CA",
    zipCode: "93762",
  },
  {
    firstName: "Tonya",
    lastName: "Grinley",
    startDate: "6/30/2022",
    department: "Marketing",
    dateOFBirth: "1/18/1996",
    street: "5956 Graedel Terrace",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11205",
  },
  {
    firstName: "Constancy",
    lastName: "Painter",
    startDate: "7/31/2022",
    department: "Sales",
    dateOFBirth: "2/24/1991",
    street: "2146 Dorton Parkway",
    city: "Boulder",
    state: "CO",
    zipCode: "80305",
  },
  {
    firstName: "Alexis",
    lastName: "Daveley",
    startDate: "2/1/2022",
    department: "Marketing",
    dateOFBirth: "12/10/1991",
    street: "2 Saint Paul Road",
    city: "Fort Wayne",
    state: "IN",
    zipCode: "46857",
  },
  {
    firstName: "Junina",
    lastName: "Sansom",
    startDate: "10/10/2022",
    department: "Services",
    dateOFBirth: "6/8/1998",
    street: "7628 Dennis Alley",
    city: "Bismarck",
    state: "ND",
    zipCode: "58505",
  },
  {
    firstName: "Enrica",
    lastName: "Maggs",
    startDate: "7/7/2022",
    department: "Services",
    dateOFBirth: "11/5/1986",
    street: "9 Merrick Lane",
    city: "Lexington",
    state: "KY",
    zipCode: "40581",
  },
  {
    firstName: "Nester",
    lastName: "Giorgio",
    startDate: "1/1/2022",
    department: "Training",
    dateOFBirth: "12/3/1993",
    street: "5 Longview Crossing",
    city: "New York City",
    state: "NY",
    zipCode: "10045",
  },
  {
    firstName: "Timothea",
    lastName: "Sacher",
    startDate: "12/3/2022",
    department: "Product Management",
    dateOFBirth: "10/26/2000",
    street: "93 Annamark Parkway",
    city: "Washington",
    state: "DC",
    zipCode: "20557",
  },
  {
    firstName: "Charlena",
    lastName: "Sowley",
    startDate: "10/25/2022",
    department: "Product Management",
    dateOFBirth: "4/11/1982",
    street: "61305 Lawn Parkway",
    city: "Irvine",
    state: "CA",
    zipCode: "92612",
  },
  {
    firstName: "Astrix",
    lastName: "Fotheringham",
    startDate: "7/7/2022",
    department: "Product Management",
    dateOFBirth: "7/12/1997",
    street: "14 Dottie Court",
    city: "Spokane",
    state: "WA",
    zipCode: "99215",
  },
  {
    firstName: "Turner",
    lastName: "Children",
    startDate: "9/26/2022",
    department: "Accounting",
    dateOFBirth: "5/23/1993",
    street: "3637 Nancy Park",
    city: "Waco",
    state: "TX",
    zipCode: "76711",
  },
  {
    firstName: "Leupold",
    lastName: "Mountstephen",
    startDate: "8/18/2022",
    department: "Training",
    dateOFBirth: "11/11/1987",
    street: "99416 Troy Terrace",
    city: "Evansville",
    state: "IN",
    zipCode: "47737",
  },
  {
    firstName: "Jaymee",
    lastName: "Snead",
    startDate: "4/3/2022",
    department: "Training",
    dateOFBirth: "6/12/1984",
    street: "48 Old Gate Road",
    city: "Dallas",
    state: "TX",
    zipCode: "75387",
  },
  {
    firstName: "Valida",
    lastName: "Hartfleet",
    startDate: "10/25/2022",
    department: "Legal",
    dateOFBirth: "11/8/1990",
    street: "9652 Anhalt Junction",
    city: "Cincinnati",
    state: "OH",
    zipCode: "45243",
  },
  {
    firstName: "Loydie",
    lastName: "Colcutt",
    startDate: "12/5/2022",
    department: "Legal",
    dateOFBirth: "2/28/1983",
    street: "3 Mayer Park",
    city: "Cleveland",
    state: "OH",
    zipCode: "44105",
  },
  {
    firstName: "Winny",
    lastName: "Hurling",
    startDate: "8/18/2022",
    department: "Product Management",
    dateOFBirth: "6/9/1990",
    street: "462 Summerview Pass",
    city: "North Las Vegas",
    state: "NV",
    zipCode: "89036",
  },
  {
    firstName: "Ervin",
    lastName: "Bartolozzi",
    startDate: "11/3/2022",
    department: "Accounting",
    dateOFBirth: "6/20/1981",
    street: "80109 Mesta Parkway",
    city: "Santa Rosa",
    state: "CA",
    zipCode: "95405",
  },
  {
    firstName: "Gawain",
    lastName: "Sherrum",
    startDate: "4/12/2022",
    department: "Sales",
    dateOFBirth: "2/23/1994",
    street: "0 Continental Way",
    city: "Knoxville",
    state: "TN",
    zipCode: "37995",
  },
  {
    firstName: "Niki",
    lastName: "Honnan",
    startDate: "9/20/2022",
    department: "Services",
    dateOFBirth: "4/30/1996",
    street: "37812 Coleman Alley",
    city: "Washington",
    state: "DC",
    zipCode: "20022",
  },
  {
    firstName: "Weidar",
    lastName: "McQuillin",
    startDate: "4/8/2022",
    department: "Engineering",
    dateOFBirth: "3/12/1990",
    street: "4 Killdeer Plaza",
    city: "Boston",
    state: "MA",
    zipCode: "02298",
  },
  {
    firstName: "Shani",
    lastName: "Tessier",
    startDate: "3/23/2022",
    department: "Sales",
    dateOFBirth: "3/31/1988",
    street: "644 Brentwood Street",
    city: "Memphis",
    state: "TN",
    zipCode: "38104",
  },
  {
    firstName: "Linnea",
    lastName: "MacCorkell",
    startDate: "1/28/2022",
    department: "Accounting",
    dateOFBirth: "8/7/1993",
    street: "34244 Hanover Park",
    city: "Rochester",
    state: "NY",
    zipCode: "14609",
  },
  {
    firstName: "Thaddus",
    lastName: "Surridge",
    startDate: "4/13/2022",
    department: "Human Resources",
    dateOFBirth: "7/16/1992",
    street: "3605 Continental Point",
    city: "Savannah",
    state: "GA",
    zipCode: "31416",
  },
  {
    firstName: "Basilio",
    lastName: "Pemberton",
    startDate: "1/23/2022",
    department: "Services",
    dateOFBirth: "10/1/1998",
    street: "3 Schmedeman Place",
    city: "Raleigh",
    state: "NC",
    zipCode: "27615",
  },
  {
    firstName: "Orren",
    lastName: "Tipton",
    startDate: "9/9/2022",
    department: "Engineering",
    dateOFBirth: "12/21/1992",
    street: "5 Myrtle Hill",
    city: "Terre Haute",
    state: "IN",
    zipCode: "47805",
  },
  {
    firstName: "Nero",
    lastName: "Jeremaes",
    startDate: "1/6/2022",
    department: "Accounting",
    dateOFBirth: "6/30/1996",
    street: "6 Dayton Circle",
    city: "Albany",
    state: "NY",
    zipCode: "12247",
  },
  {
    firstName: "Finn",
    lastName: "Balden",
    startDate: "2/16/2022",
    department: "Sales",
    dateOFBirth: "12/19/1995",
    street: "01399 Mcguire Plaza",
    city: "Inglewood",
    state: "CA",
    zipCode: "90398",
  },
  {
    firstName: "Kissiah",
    lastName: "Stanner",
    startDate: "7/21/2022",
    department: "Support",
    dateOFBirth: "1/19/1986",
    street: "7311 Southridge Crossing",
    city: "Lansing",
    state: "MI",
    zipCode: "48919",
  },
  {
    firstName: "Harwell",
    lastName: "Oak",
    startDate: "4/25/2022",
    department: "Services",
    dateOFBirth: "4/21/1998",
    street: "2063 Gulseth Park",
    city: "Houston",
    state: "TX",
    zipCode: "77288",
  },
  {
    firstName: "Rosemaria",
    lastName: "Bonner",
    startDate: "11/21/2022",
    department: "Research and Development",
    dateOFBirth: "8/15/1997",
    street: "72930 Buena Vista Road",
    city: "Columbus",
    state: "OH",
    zipCode: "43231",
  },
  {
    firstName: "Loretta",
    lastName: "Anthony",
    startDate: "10/28/2022",
    department: "Legal",
    dateOFBirth: "10/30/1995",
    street: "0 Bunker Hill Pass",
    city: "Cleveland",
    state: "OH",
    zipCode: "44177",
  },
  {
    firstName: "Pet",
    lastName: "Chippindale",
    startDate: "3/20/2022",
    department: "Training",
    dateOFBirth: "10/10/1981",
    street: "830 Oak Parkway",
    city: "Hartford",
    state: "CT",
    zipCode: "06120",
  },
];
